name: Hexlet CI app deploy workflow
on: push
jobs:
    deploy-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: '>=18'
            
            - name: "Setup project dependances and build it"
              run: make setup
            
            - name: "Run project tests"
              run: make test
            
            - name: "Run project linting"
              run: make lint
    